export {
  COUNTRY_INDEX,
  COUNTRY_INDEX_CREATE,
  COUNTRY_INDEX_UPDATE,
  COUNTRY_INDEX_DETAIL,
  COUNTRY_LABEL,
  COUNTRY_LABEL_UPDATE,
  COUNTRY_LABEL_DETAIL,
} from './countries';

export {
  GENDER_INDEX,
  GENDER_INDEX_CREATE,
  GENDER_INDEX_UPDATE,
  GENDER_INDEX_DETAIL,
  GENDER_LABEL,
  GENDER_LABEL_UPDATE,
  GENDER_LABEL_DETAIL,
} from './genders';

export {
  LANGUAGE_INDEX,
  LANGUAGE_INDEX_UPDATE,
  LANGUAGE_INDEX_DETAIL,
  LANGUAGE_LABEL_UPDATE,
  LANGUAGE_LABEL,
  LANGUAGE_LABEL_DETAIL,
} from './languages';

export {
  PERSON_INDEX,
  PERSON_LABEL,
  PERSON_LABEL_UPDATE,
  PERSON_INDEX_UPDATE,
  PERSON_INDEX_DETAIL,
  PERSON_INDEX_CREATE,
  PERSON_LABEL_DETAIL,
} from './persons';

export {
  REGION_INDEX,
  REGION_INDEX_CREATE,
  REGION_INDEX_UPDATE,
  REGION_INDEX_DETAIL,
  REGION_LABEL,
  REGION_LABEL_UPDATE,
  REGION_LABEL_DETAIL,
} from './regions';

export {
  USER_GROUP_INDEX,
  USER_GROUP_INDEX_CREATE,
  USER_GROUP_INDEX_UPDATE,
  USER_GROUP_INDEX_DETAIL,
  USER_GROUP_LABEL,
  USER_GROUP_LABEL_UPDATE,
  USER_GROUP_LABEL_DETAIL,
} from './user-group';

export { PERMISSION_INDEX } from './permission';

export {
  PERSON_UPLOAD_INDEX,
  PERSON_UPLOAD_LABEL,
  PERSON_UPLOAD_LABEL_UPDATE,
  PERSON_UPLOAD_INDEX_UPDATE,
  PERSON_UPLOAD_INDEX_DETAIL,
  PERSON_UPLOAD_INDEX_CREATE,
  PERSON_UPLOAD_LABEL_DETAIL,
} from './person-uploads';

export {
  MESSAGE_INDEX,
  MESSAGE_INDEX_UPDATE,
  MESSAGE_INDEX_DETAIL,
  MESSAGE_LABEL,
  MESSAGE_LABEL_UPDATE,
  MESSAGE_LABEL_DETAIL,
} from './message';

export {
  SYS_ATT_MAIN_INDEX,
  SYS_ATT_MAIN_INDEX_CREATE,
  SYS_ATT_MAIN_INDEX_UPDATE,
  SYS_ATT_MAIN_INDEX_DETAIL,
  SYS_ATT_MAIN_LABEL,
  SYS_ATT_MAIN_LABEL_UPDATE,
  SYS_ATT_MAIN_LABEL_DETAIL,
} from './sys-att-main';

export {
  SYS_ATT_SUB_INDEX,
  SYS_ATT_SUB_INDEX_CREATE,
  SYS_ATT_SUB_INDEX_UPDATE,
  SYS_ATT_SUB_INDEX_DETAIL,
  SYS_ATT_SUB_LABEL,
  SYS_ATT_SUB_LABEL_UPDATE,
  SYS_ATT_SUB_LABEL_DETAIL,
} from './sys-att-sub';
