export const PERSON_UPLOAD_INDEX = {
  text_title: 'rel_person_uploads.index.title',

  button_export: 'rel_person_uploads.index.button_export',
  button_pdf: 'rel_person_uploads.index.button_pdf',
  button_csv: 'rel_person_uploads.index.button_csv',
  button_excel: 'rel_person_uploads.index.button_excel',
  button_export_all_data: 'rel_person_uploads.index.button_export_all_data',
  button_export_current_page: 'rel_person_uploads.index.button_export_current_page',
  button_export_search_data: 'rel_person_uploads.index.button_export_search_data',
  button_import: 'rel_person_uploads.index.button_import',
  button_create: 'rel_person_uploads.index.button_create',

  column_id: 'rel_person_uploads.index.column_id',
  column_name: 'rel_person_uploads.index.column_name',
  column_code: 'rel_person_uploads.index.column_code',
  column_icon: 'rel_person_uploads.index.column_icon',
  column_date_format: 'rel_person_uploads.index.column_date_format',
  column_culture: 'rel_person_uploads.index.column_culture',
  column_is_active: 'rel_person_uploads.index.column_is_active',
  column_sort: 'rel_person_uploads.index.column_sort',
  column_action: 'rel_person_uploads.index.column_action',
  column_lastName: 'rel_person_uploads.index.column_lastName',
  column_middleName: 'rel_person_uploads.index.column_middleName',
  column_firstName: 'rel_person_uploads.index.column_firstName',
  column_gender: 'rel_person_uploads.index.column_gender',
  column_address: 'rel_person_uploads.index.column_address',
  column_zipcode: 'rel_person_uploads.index.column_zipcode',
  column_place: 'rel_person_uploads.index.column_place',
  column_country: 'rel_person_uploads.index.column_country',
  column_region: 'rel_person_uploads.index.column_region',
  column_latitude: 'rel_person_uploads.index.column_latitude',
  column_longtitude: 'rel_person_uploads.index.column_longtitude',
  column_telephone1: 'rel_person_uploads.index.column_telephone1',
  column_telephone2: 'rel_person_uploads.index.column_telephone2',
  column_email1: 'rel_person_uploads.index.column_email1',
  column_email2: 'rel_person_uploads.index.column_email2',
  column_memo: 'rel_person_uploads.index.column_memo',
  column_memoAdministration: 'rel_person_uploads.index.column_memoAdministration',
  column_wantsNewsletter: 'rel_person_uploads.index.column_wantsNewsletter',
  column_person: 'rel_person_uploads.index.column_person',
  column_name_rel_person: 'rel_person_uploads.index.column_name_rel_person',
  column_id_rel_person: 'rel_person_uploads.index.column_id_rel_person',
  column_action_rel_person: 'rel_person_uploads.index.column_action_rel_person',
  column_upload_file: 'rel_person_uploads.index.column_upload_file',

  paginate_total_page: 'rel_person_uploads.index.paginate_total_page',
  paginate_rows_per_page: 'rel_person_uploads.index.paginate_rows_per_page',
  paginate_go_to: 'rel_person_uploads.index.goto_page',
  paginate_show: 'rel_person_uploads.index.paginate_show',
  paginate_of: 'rel_person_uploads.index.paginate_of',

  tooltip_switch: 'rel_person_uploads.index.tooltip_switch',
  tooltip_search: 'rel_person_uploads.index.tooltip_search',
  tooltip_filter: 'rel_person_uploads.index.tooltip_filter',
  tooltip_show_hide_column: 'rel_person_uploads.index.tooltip_show_hide_column',
  tooltip_update: 'rel_person_uploads.index.tooltip_update',
  tooltip_create: 'rel_person_uploads.index.tooltip_create',
  tooltip_delete: 'rel_person_uploads.index.tooltip_delete',
  tooltip_detail: 'rel_person_uploads.index.tooltip_detail',
  tooltip_expand: 'rel_person_uploads.index.tooltip_expand',
};

export const PERSON_UPLOAD_INDEX_CREATE = {
  text_title: 'rel_person_uploads.create.title',

  button_close: 'rel_person_uploads.create.button_close',
  button_back: 'rel_person_uploads.create.button_back',
  button_save: 'rel_person_uploads.create.button_save',

  column_lastName: 'rel_person_uploads.create.column_lastName',
  column_middleName: 'rel_person_uploads.create.column_middleName',
  column_firstName: 'rel_person_uploads.create.column_firstName',
  column_gender: 'rel_person_uploads.create.column_gender',
  column_address: 'rel_person_uploads.create.column_address',
  column_zipcode: 'rel_person_uploads.create.column_zipcode',
  column_place: 'rel_person_uploads.create.column_place',
  column_country: 'rel_person_uploads.create.column_country',
  column_region: 'rel_person_uploads.create.column_region',
  column_latitude: 'rel_person_uploads.create.column_latitude',
  column_longtitude: 'rel_person_uploads.create.column_longtitude',
  column_telephone1: 'rel_person_uploads.create.column_telephone1',
  column_telephone2: 'rel_person_uploads.create.column_telephone2',
  column_email1: 'rel_person_uploads.create.column_email1',
  column_email2: 'rel_person_uploads.create.column_email2',
  column_memo: 'rel_person_uploads.create.column_memo',
  column_memoAdministration: 'rel_person_uploads.create.column_memoAdministration',
  column_wantsNewsletter: 'rel_person_uploads.create.column_wantsNewsletter',
  column_person: 'rel_person_uploads.create.column_person',
  column_person_name: 'rel_person_uploads.create.column_person_name'
};

export const PERSON_UPLOAD_INDEX_UPDATE = {
  text_title: 'rel_person_uploads.update.title',

  button_close: 'rel_person_uploads.update.button_close',
  button_back: 'rel_person_uploads.update.button_back',
  button_save: 'rel_person_uploads.update.button_save',

  column_lastName: 'rel_person_uploads.update.column_lastName',
  column_middleName: 'rel_person_uploads.update.column_middleName',
  column_firstName: 'rel_person_uploads.update.column_firstName',
  column_gender: 'rel_person_uploads.update.column_gender',
  column_address: 'rel_person_uploads.update.column_address',
  column_zipcode: 'rel_person_uploads.update.column_zipcode',
  column_place: 'rel_person_uploads.update.column_place',
  column_country: 'rel_person_uploads.update.column_country',
  column_region: 'rel_person_uploads.update.column_region',
  column_latitude: 'rel_person_uploads.update.column_latitude',
  column_longtitude: 'rel_person_uploads.update.column_longtitude',
  column_telephone1: 'rel_person_uploads.update.column_telephone1',
  column_telephone2: 'rel_person_uploads.update.column_telephone2',
  column_email1: 'rel_person_uploads.update.column_email1',
  column_email2: 'rel_person_uploads.update.column_email2',
  column_memo: 'rel_person_uploads.update.column_memo',
  column_memoAdministration: 'rel_person_uploads.update.column_memoAdministration',
  column_wantsNewsletter: 'rel_person_uploads.update.column_wantsNewsletter',
  column_person: 'rel_person_uploads.update.column_person',
  column_person_name: 'rel_person_uploads.update.column_person_name'
};

export const PERSON_UPLOAD_INDEX_DETAIL = {
  text_title: 'rel_person_uploads.detail.title',

  button_close: 'rel_person_uploads.detail.button_close',
  button_back: 'rel_person_uploads.detail.button_back',

  column_lastName: 'rel_person_uploads.detail.column_lastName',
  column_middleName: 'rel_person_uploads.detail.column_middleName',
  column_firstName: 'rel_person_uploads.detail.column_firstName',
  column_gender: 'rel_person_uploads.detail.column_gender',
  column_address: 'rel_person_uploads.detail.column_address',
  column_zipcode: 'rel_person_uploads.detail.column_zipcode',
  column_place: 'rel_person_uploads.detail.column_place',
  column_country: 'rel_person_uploads.detail.column_country',
  column_region: 'rel_person_uploads.detail.column_region',
  column_latitude: 'rel_person_uploads.detail.column_latitude',
  column_longtitude: 'rel_person_uploads.detail.column_longtitude',
  column_telephone1: 'rel_person_uploads.detail.column_telephone1',
  column_telephone2: 'rel_person_uploads.detail.column_telephone2',
  column_email1: 'rel_person_uploads.detail.column_email1',
  column_email2: 'rel_person_uploads.detail.column_email2',
  column_memo: 'rel_person_uploads.detail.column_memo',
  column_memoAdministration: 'rel_person_uploads.detail.column_memoAdministration',
  column_wantsNewsletter: 'rel_person_uploads.detail.column_wantsNewsletter',
  column_person: 'rel_person_uploads.detail.column_person',
  column_person_name: 'rel_person_uploads.detail.column_person_name'
};

export const PERSON_UPLOAD_LABEL = {
  text_title: 'rel_person_uploads.label.title',

  button_export: 'rel_person_uploads.label.button_export',
  button_pdf: 'rel_person_uploads.label.button_pdf',
  button_csv: 'rel_person_uploads.label.button_csv',
  button_excel: 'rel_person_uploads.label.button_excel',
  button_export_all_data: 'rel_person_uploads.label.button_export_all_data',
  button_export_current_page: 'rel_person_uploads.label.button_export_current_page',
  button_export_search_data: 'rel_person_uploads.label.button_export_search_data',
  button_import: 'rel_person_uploads.label.button_import',

  column_id: 'rel_person_uploads.label.column_id',
  column_name: 'rel_person_uploads.label.column_name',
  column_code: 'rel_person_uploads.label.column_code',
  column_sort: 'rel_person_uploads.label.column_sort',
  column_action: 'rel_person_uploads.label.column_action',
  paginate_total_page: 'rel_person_uploads.label.paginate_total_page',
  paginate_rows_per_page: 'rel_person_uploads.label.paginate_rows_per_page',
  paginate_go_to: 'rel_person_uploads.label.goto_page',
  paginate_show: 'rel_person_uploads.label.paginate_show',
  paginate_of: 'rel_person_uploads.label.paginate_of',

  tooltip_switch: 'rel_person_uploads.label.tooltip_switch',
  tooltip_search: 'rel_person_uploads.label.tooltip_search',
  tooltip_filter: 'rel_person_uploads.label.tooltip_filter',
  tooltip_show_hide_column: 'rel_person_uploads.label.tooltip_show_hide_column',
  tooltip_update: 'rel_person_uploads.label.tooltip_update',
  tooltip_detail: 'rel_person_uploads.label.tooltip_detail',
};

export const PERSON_UPLOAD_LABEL_UPDATE = {
  text_title: 'rel_person_uploads.edit_label.title',

  button_close: 'rel_person_uploads.edit_label.button_close',
  button_back: 'rel_person_uploads.edit_label.button_back',
  button_save: 'rel_person_uploads.edit_label.button_save',
  column_id: 'rel_person_uploads.edit_label.column_id',
  column_name: 'rel_person_uploads.edit_label.column_name',
  column_code: 'rel_person_uploads.edit_label.column_code',
  column_sort: 'rel_person_uploads.edit_label.column_sort',
  column_action: 'rel_person_uploads.edit_label.column_action',
};

export const PERSON_UPLOAD_LABEL_DETAIL = {
  text_title: 'rel_person_uploads.detail.title',

  button_close: 'rel_person_uploads.detail.button_close',
  button_back: 'rel_person_uploads.detail.button_back',
  button_save: 'rel_person_uploads.detail.button_save',
  column_id: 'rel_person_uploads.detail.column_id',
  column_name: 'rel_person_uploads.detail.column_name',
  column_code: 'rel_person_uploads.detail.column_code',
  column_sort: 'rel_person_uploads.detail.column_sort',
  column_action: 'rel_person_uploads.detail.column_action',
};

export default {
  PERSON_UPLOAD_INDEX,
  PERSON_UPLOAD_LABEL,
  PERSON_UPLOAD_LABEL_UPDATE,
  PERSON_UPLOAD_LABEL_DETAIL,
  PERSON_UPLOAD_INDEX_UPDATE,
  PERSON_UPLOAD_INDEX_CREATE,
  PERSON_UPLOAD_INDEX_DETAIL,
};
