const TYPES = {
  ASIDE_TOGGLE: 'ASIDE_TOGGLE',
  ASIDE_CHANGE: 'ASIDE_CHANGE',
  BREADCRUMB_CHANGE: 'BREADCRUMB_CHANGE',
  PAGE_CHANGE_HEADER_TITLE: 'PAGE_CHANGE_HEADER_TITLE',
  PAGE_CHANGE_THEME: 'PAGE_CHANGE_THEME',
  SIDEMENU_TOGGLE: 'SIDEMENU_TOGGLE',
  SIDEMENU_CHANGE: 'SIDEMENU_CHANGE',
  SIDEMENU_UPDATE: 'SIDEMENU_UPDATE',
  FIREBASE_CHANGE: 'FIREBASE_CHANGE',
  TOKEN_CHANGE: 'TOKEN_CHANGE',

  LANGUAGE_STATE: 'LANGUAGE_STATE',
  LANGUAGE_LIST: 'LANGUAGE_LIST',
  LANGUAGE_LABEL: 'LANGUAGE_LABEL',
  LANGUAGE_LABEL_SUCCESS: 'LANGUAGE_LABEL_SUCCESS',

  IS_SWITCH_LABEL: 'IS_SWITCH_LABEL',
  UPDATE_SWITCH_LABEL: 'UPDATE_SWITCH_LABEL',

  GENDER_STATE: 'GENDER_STATE',
  GENDER_LABEL: 'GENDER_LABEL',
  GENDER_LABEL_SUCCESS: 'GENDER_LABEL_SUCCESS',

  PERSON_STATE: 'PERSON_STATE',
  PERSON_LABEL: 'PERSON_LABEL',
  PERSON_LABEL_SUCCESS: 'PERSON_LABEL_SUCCESS',

  CURRENT_LANGUAGE: 'CURRENT_LANGUAGE',
  CURRENT_LANGUAGE_LIST: 'CURRENT_LANGUAGE_LIST',
  LANGUAGE: 'LANGUAGE',

  QUICK_EDIT: 'QUICK_EDIT',
  SAVE_LABEL: 'SAVE_LABEL',
  SAVE_USER: 'SAVE_USER',
};

export default TYPES;
