export const LANGUAGE_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'id',
    code: 'column_id',
    sortable: true,
    visibility: true,
    export: true,
    label: 'id',
  },
  {
    key: 'name',
    code: 'column_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'name',
  },
  {
    key: 'code',
    code: 'column_code',
    sortable: true,
    visibility: true,
    export: true,
    label: 'code',
  },
  {
    key: 'icon',
    code: 'column_icon',
    sortable: false,
    visibility: true,
    export: true,
    label: 'icon',
  },
  {
    key: 'date_formart',
    code: 'column_date_format',
    sortable: false,
    visibility: true,
    export: true,
    label: 'dateFormat',
  },
  {
    key: 'culture',
    code: 'column_culture',
    sortable: true,
    visibility: true,
    export: true,
    label: 'culture',
  },
  {
    key: 'is_active',
    code: 'column_is_active',
    sortable: false,
    visibility: true,
    export: true,
    label: 'isActive',
  },
  {
    key: 'sort',
    code: 'column_sort',
    sortable: true,
    visibility: true,
    export: true,
    label: 'sort',
  },
];

export const LANGUAGE_LABEL_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'name',
    code: 'column_name',
    sortable: true,
    visibility: false,
    export: true,
    label: 'name',
  },
  {
    key: 'code',
    code: 'column_code',
    sortable: true,
    visibility: true,
    export: true,
    label: 'code',
  },
  {
    key: 'sort',
    code: 'column_sort',
    sortable: false,
    visibility: true,
    export: true,
    label: 'sort',
  },
];
