export const PERSON_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'id',
    code: 'column_id',
    sortable: true,
    visibility: true,
    export: true,
    label: 'id',
  },
  {
    key: 'last_name',
    code: 'column_last_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'lastName',
  },
  {
    key: 'middle_name',
    code: 'column_middle_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'middleName',
  },
  {
    key: 'first_name',
    code: 'column_first_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'firstName',
  },
  {
    key: 'gender_name',
    code: 'column_gender',
    sortable: true,
    visibility: true,
    export: true,
    label: 'genderName',
  },
  {
    key: 'address',
    code: 'column_address',
    sortable: true,
    visibility: true,
    export: true,
    label: 'address',
  },
  {
    key: 'place',
    code: 'column_place',
    sortable: true,
    visibility: true,
    export: true,
    label: 'place',
  },
  {
    key: 'telephone1',
    code: 'column_telephone1',
    sortable: true,
    visibility: true,
    export: true,
    label: 'telephone1',
  },
  {
    key: 'telephone2',
    code: 'column_telephone2',
    sortable: true,
    visibility: true,
    export: true,
    label: 'telephone2',
  },
  {
    key: 'email1',
    code: 'column_email1',
    sortable: true,
    visibility: true,
    export: true,
    label: 'email1',
  },
  {
    key: 'email2',
    code: 'column_email2',
    sortable: true,
    visibility: true,
    export: true,
    label: 'email2',
  },
  {
    key: 'zipcode',
    code: 'column_zipcode',
    sortable: true,
    visibility: true,
    export: true,
    label: 'zipcode',
  },
  {
    key: 'memo',
    code: 'column_memo',
    sortable: true,
    visibility: false,
    export: false,
    label: 'memo',
  },
  {
    key: 'memoAdministration',
    code: 'column_memoAdministration',
    sortable: true,
    visibility: false,
    export: false,
    label: 'memoAdministration',
  },
  {
    key: 'wantsNewsletter',
    code: 'column_wantsNewsletter',
    sortable: true,
    visibility: false,
    export: false,
    label: 'wantsNewsletter',
  },
];

export const PERSON_LABEL_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'name',
    code: 'column_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'name',
  },
  {
    key: 'code',
    code: 'column_code',
    sortable: true,
    visibility: true,
    export: true,
    label: 'code',
  },
  {
    key: 'sort',
    code: 'column_sort',
    sortable: true,
    visibility: true,
    export: true,
    label: 'sort',
  },
];
