export const USER_GROUP_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'id',
    code: 'column_id',
    sortable: true,
    visibility: true,
    export: true,
    label: 'id',
  },
  {
    key: 'name',
    code: 'column_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'name',
  },
  {
    key: 'group_title',
    code: 'column_group_title',
    sortable: true,
    visibility: true,
    export: true,
    label: 'groupTitle',
  },
  {
    key: 'description',
    code: 'column_description',
    sortable: true,
    visibility: true,
    export: true,
    label: 'description',
  },
  {
    key: 'is_active',
    code: 'column_is_active',
    sortable: false,
    visibility: true,
    export: true,
    label: 'isActive',
  },
];

export const USER_GROUP_LABEL_COLUMN = [
  {
    key: 'action',
    code: 'column_action',
    sortable: false,
    visibility: true,
    export: true,
    label: 'action',
  },
  {
    key: 'name',
    code: 'column_name',
    sortable: true,
    visibility: true,
    export: true,
    label: 'name',
  },
  {
    key: 'code',
    code: 'column_code',
    sortable: true,
    visibility: true,
    export: true,
    label: 'code',
  },
  {
    key: 'sort',
    code: 'column_sort',
    sortable: true,
    visibility: true,
    export: true,
    label: 'sort',
  },
];
